version: '3'
services:
  node:
    build: node/.
    volumes:
      - ./node:/app
    ports:
    - '8081:8081'
    restart: always
    depends_on:
    - mysqldb
    links:
    - mysqldb
    environment:
    - MYSQL_HOST=mysqldb
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
    - MYSQL_DATABASE=test
    - MYSQL_ROOT_PASSWORD=root

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    command: mysqld --user=root --verbose
    volumes:
       - ./schemadump.sql:/docker-entrypoint-initdb.d/schemadump.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
